# --- General options --- #
url: "https://dieghernan.github.io"
baseurl: ""
github_repo: "https://github.com/dieghernan/dieghernan.github.io/"

title: One world
description: Projects, maps & coding

wordspermin: 180.0

# --- Collections --- #
collections:
  projects:
    output: true
    permalink: /projects/:name/

# --- Navigation bar options --- #
navbar-links:
  Blog:
    - Posts: "blog"
    - Tags: "tags"
    - Archive: "archive"
  Projects:
    - All: "projects"
    - COVID19 in Spain Microsite: "https://dieghernan.github.io/COVID19/"
    - Country Codes & Organizations: "https://dieghernan.github.io/Country-Codes-and-International-Organizations/"
    - Textwatch Clima: "https://dieghernan.github.io/TextWatchClima/"
  Gallery: "gallery"
  View on Github: "https://github.com/dieghernan/dieghernan.github.io"

avatar: "/assets/img/avatar-icon.png"

# --- Background colour/image options --- #
navbar-col: "#008080"
navbar-text-col: "#FFFFFF"
navbar-children-col: "#00A0A0"
page-col: "#FFFFFF"
link-col: "#008080"
hover-col: "#DBE9E9"
footer-col: "#008080"
footer-text-col: "#FFFFFF"
footer-link-col: "#15403F"
background-light-col: "#F3F8F8"

# --- Footer options --- #
author:
  name: dieghernan

social-network-links:
  rss: true
  stackoverflow: 7877917/dieghernan
  github: dieghernan
  carto: dieghernan
  reddit: dieghernan
  rpubs: dieghernan
  wikicommons: dieghernan84

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# --- Web Statistics Section --- #
google_analytics: "UA-139034853-1"


# --- Comments --- #
disqus: dieghernan

excerpt_length: 10

# Character used to separate site title and description in HTML document title and RSS
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Madrid"
markdown: kramdown
highlighter: rouge
permalink: /:year:month_:title/
paginate: 4
paginate_path: "/blog/page:num/"

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      share-img: https://dieghernan.github.io/assets/img/headerblog.png
      postedby: dieghernan
      includeonfeed: true
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true
      share-img: https://dieghernan.github.io/assets/img/headerblog.png
      date: 2001-01-01
      includeonfeed: true
  -
    scope:
      path: "assets/figs"
    values:
      image: true


# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - vendor


# prose.io config
prose:
  siteurl: 'https://dieghernan.github.io/'
  rooturl: '_posts'
  media: 'img'
  ignore:
    - LICENSE
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /js
    
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."
          
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
 

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
